### ISSUE TITLE
Help doesn't show Tutorials, Guides and the like

### ISSUE THREAD

**Issue by clfest** [madskjeldgaard/fzf-sc#11]
‘FzfSC help’ gets me at the classes, but as a contrast to the Qt Help it doesn’t seem to get at the Guides, Tutorials and whatnot. How do I get at them and get them properly processed for NeoVim?

                                           Thank You For Your Attention

**Comment by madskjeldgaard** [comment]
Hi, this is a problem with scnvim, not fzf-sc, see https://github.com/davidgranstrom/scnvim/issues/59
