### ISSUE TITLE
fzf-sc was not found

### ISSUE THREAD

**Issue by gilfuser** [madskjeldgaard/fzf-sc#6]
Hello!
Thank you for this project. I'm looking forward to try it myself!

I'm getting an error while trying to add fzf-sc to SCNvim.
If I put `scnvim.load_extension('fzf-sc')`
after 

```
scnvim.setup {
  extensions = {
    ['fzf-sc'] = {
      search_plugin = 'fzf-lua',
    },
  }
}
```
this is what I get:
```
Error detected while processing /home/skmecs/.config/nvim/init.lua:
E5113: Error while calling lua chunk: .../site/pack/packer/start/scnvim/lua/scnvim/extensions.lua:38: [scnvim] "fzf-sc" was not found
stack traceback:
        [C]: in function 'error'
        .../site/pack/packer/start/scnvim/lua/scnvim/extensions.lua:38: in function 'load_extension'
        .../site/pack/packer/start/scnvim/lua/scnvim/extensions.lua:49: in function '__index'
        .../site/pack/packer/start/scnvim/lua/scnvim/extensions.lua:68: in function 'load_extension'
        /home/skmecs/.config/nvim/lua/plugins_configs/scnvim.lua:53: in main chunk
        [C]: in function 'require'
        /home/skmecs/.config/nvim/init.lua:26: in main chunk
```

I'm trying to use fzf-lua instead of nvim-fzf. Could be that the problem?
I tried fzf-lua and it's working fine.

thank you in advance

all the best,
Gil

**Comment by madskjeldgaard** [comment]
Hi Gil! Sorry you're having trouble. Did you remember to add the extension load line ? 

```
scnvim.load_extension('fzf-sc')

```

**Comment by madskjeldgaard** [comment]
> Hi Gil! Sorry you're having trouble. Did you remember to add the extension load line ?
> 
> ```
> scnvim.load_extension('fzf-sc')
> ```

As described here https://github.com/madskjeldgaard/fzf-sc#setup

**Comment by gilfuser** [comment]
Hi Mads.
Yes, I did add the extension load line, just as in the description. After the setup function.

**Comment by gilfuser** [comment]
I reorganized my plugins and reinstalled them. I'm not sure what made it work or what was the problem exactly
